# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 666)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblsong = QtWidgets.QLabel(self.centralwidget)
        self.lblsong.setGeometry(QtCore.QRect(610, 280, 271, 31))
        self.lblsong.setObjectName("lblsong")
        self.lbl_namemusic = QtWidgets.QLabel(self.centralwidget)
        self.lbl_namemusic.setGeometry(QtCore.QRect(510, 0, 171, 31))
        self.lbl_namemusic.setObjectName("lbl_namemusic")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(520, 290, 55, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 330, 55, 21))
        self.label_2.setObjectName("label_2")
        self.lblalbum = QtWidgets.QLabel(self.centralwidget)
        self.lblalbum.setGeometry(QtCore.QRect(610, 325, 281, 21))
        self.lblalbum.setObjectName("lblalbum")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(520, 360, 55, 21))
        self.label_4.setObjectName("label_4")
        self.lblartist = QtWidgets.QLabel(self.centralwidget)
        self.lblartist.setGeometry(QtCore.QRect(610, 360, 271, 21))
        self.lblartist.setObjectName("lblartist")
        self.lbl_titletabel = QtWidgets.QLabel(self.centralwidget)
        self.lbl_titletabel.setGeometry(QtCore.QRect(140, 0, 111, 21))
        self.lbl_titletabel.setObjectName("lbl_titletabel")
        self.lblimage = QtWidgets.QLabel(self.centralwidget)
        self.lblimage.setGeometry(QtCore.QRect(510, 70, 251, 191))
        self.lblimage.setText("")
        self.lblimage.setPixmap(QtGui.QPixmap(":/icons/music_play.png"))
        self.lblimage.setScaledContents(True)
        self.lblimage.setWordWrap(False)
        self.lblimage.setObjectName("lblimage")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 510, 471, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_stop.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_stop.setIcon(icon)
        self.btn_stop.setIconSize(QtCore.QSize(37, 48))
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        self.btn_prev = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_prev.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon1)
        self.btn_prev.setIconSize(QtCore.QSize(48, 48))
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout_2.addWidget(self.btn_prev)
        self.btn_play = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon2)
        self.btn_play.setIconSize(QtCore.QSize(37, 48))
        self.btn_play.setCheckable(False)
        self.btn_play.setAutoRepeat(False)
        self.btn_play.setAutoDefault(False)
        self.btn_play.setDefault(False)
        self.btn_play.setFlat(False)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_2.addWidget(self.btn_play)
        self.btn_pause = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_pause.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause.setIcon(icon3)
        self.btn_pause.setIconSize(QtCore.QSize(40, 48))
        self.btn_pause.setCheckable(False)
        self.btn_pause.setAutoRepeat(False)
        self.btn_pause.setAutoDefault(False)
        self.btn_pause.setDefault(False)
        self.btn_pause.setFlat(False)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout_2.addWidget(self.btn_pause)
        self.btn_next = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon4)
        self.btn_next.setIconSize(QtCore.QSize(48, 48))
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout_2.addWidget(self.btn_next)
        self.btn_shuffle = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_shuffle.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/shuffle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_shuffle.setIcon(icon5)
        self.btn_shuffle.setIconSize(QtCore.QSize(37, 48))
        self.btn_shuffle.setCheckable(False)
        self.btn_shuffle.setObjectName("btn_shuffle")
        self.horizontalLayout_2.addWidget(self.btn_shuffle)
        self.btn_repeat = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_repeat.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/repeatOne.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_repeat.setIcon(icon6)
        self.btn_repeat.setIconSize(QtCore.QSize(37, 48))
        self.btn_repeat.setCheckable(False)
        self.btn_repeat.setChecked(False)
        self.btn_repeat.setObjectName("btn_repeat")
        self.horizontalLayout_2.addWidget(self.btn_repeat)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 440, 811, 67))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbltimeplay = QtWidgets.QLabel(self.layoutWidget1)
        self.lbltimeplay.setObjectName("lbltimeplay")
        self.horizontalLayout_3.addWidget(self.lbltimeplay)
        self.slider_play = QtWidgets.QSlider(self.layoutWidget1)
        self.slider_play.setOrientation(QtCore.Qt.Horizontal)
        self.slider_play.setObjectName("slider_play")
        self.horizontalLayout_3.addWidget(self.slider_play)
        self.lblfulltime = QtWidgets.QLabel(self.layoutWidget1)
        self.lblfulltime.setObjectName("lblfulltime")
        self.horizontalLayout_3.addWidget(self.lblfulltime)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setGeometry(QtCore.QRect(780, 530, 131, 22))
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.musicList = QtWidgets.QListView(self.centralwidget)
        self.musicList.setGeometry(QtCore.QRect(50, 20, 271, 411))
        self.musicList.setObjectName("musicList")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 520, 41, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/vlm.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.lbl_playmode = QtWidgets.QLabel(self.centralwidget)
        self.lbl_playmode.setGeometry(QtCore.QRect(580, 570, 81, 21))
        self.lbl_playmode.setObjectName("lbl_playmode")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 120, 47, 139))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_addsong = QtWidgets.QPushButton(self.widget)
        self.btn_addsong.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_addsong.setIcon(icon7)
        self.btn_addsong.setIconSize(QtCore.QSize(32, 32))
        self.btn_addsong.setObjectName("btn_addsong")
        self.verticalLayout_2.addWidget(self.btn_addsong)
        self.btn_delsong = QtWidgets.QPushButton(self.widget)
        self.btn_delsong.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delsong.setIcon(icon8)
        self.btn_delsong.setIconSize(QtCore.QSize(32, 32))
        self.btn_delsong.setObjectName("btn_delsong")
        self.verticalLayout_2.addWidget(self.btn_delsong)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(20, 440, 51, 81))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_incSpeed = QtWidgets.QPushButton(self.widget1)
        self.btn_incSpeed.setObjectName("btn_incSpeed")
        self.horizontalLayout.addWidget(self.btn_incSpeed)
        self.btn_decSpeed = QtWidgets.QPushButton(self.widget1)
        self.btn_decSpeed.setObjectName("btn_decSpeed")
        self.horizontalLayout.addWidget(self.btn_decSpeed)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lblspeed = QtWidgets.QLabel(self.widget1)
        self.lblspeed.setObjectName("lblspeed")
        self.verticalLayout.addWidget(self.lblspeed)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionMake_PlayList = QtWidgets.QAction(MainWindow)
        self.actionMake_PlayList.setObjectName("actionMake_PlayList")
        self.actionMake = QtWidgets.QAction(MainWindow)
        self.actionMake.setObjectName("actionMake")
        self.menuFile.addAction(self.actionMake_PlayList)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblsong.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ff0000;\">.....</span></p></body></html>"))
        self.lbl_namemusic.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#5500ff;\">Song Name</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">song</span></p><p><span style=\" font-size:10pt;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Album</span></p><p><br/></p></body></html>"))
        self.lblalbum.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#0055ff;\">.....</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Artist</span></p></body></html>"))
        self.lblartist.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffaa00;\">.....</span></p></body></html>"))
        self.lbl_titletabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\">Queued Song</span></p><p><span style=\" font-size:9pt; font-weight:600; color:#0000ff;\"><br/></span></p></body></html>"))
        self.lbltimeplay.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">00:00</span></p><p><br/></p></body></html>"))
        self.lblfulltime.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">00:00</span></p><p><br/></p></body></html>"))
        self.lbl_playmode.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">,,,,</span></p></body></html>"))
        self.btn_incSpeed.setText(_translate("MainWindow", "+"))
        self.btn_decSpeed.setText(_translate("MainWindow", "-"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Speed</span></p></body></html>"))
        self.lblspeed.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">1.0</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionMake_PlayList.setText(_translate("MainWindow", "Make PlayList"))
        self.actionMake.setText(_translate("MainWindow", "Make"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
